default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trackr_api_development
  username: <%= ENV['DB_USERNAME'] || Rails.application.credentials[Rails.env.to_sym][:db][:username] %>
  password: <%= ENV['DB_PASSWORD'] || Rails.application.credentials[Rails.env.to_sym][:db][:password] %>

test:
  <<: *default
  database: trackr_api_test
