default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trackr_api_development

test:
  <<: *default
  database: trackr_api_test

production:
  <<: *default
  database: trackr_api_production
  username: trackr_api
  password: <%= Rails.application.credentials[Rails.env.to_sym][:db_password] %>
