default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trackr_api_development

test:
  <<: *default
  database: trackr_api_test

production:
  <<: *default
  database: trackr_api_production
  username: <%= Credentials.get :db, :username %>
  password: <%= Credentials.get :db, :password %>
  host: <%= Credentials.get :db, :host %>
